### ISSUE TITLE
CPMU dashboard- pmu monthly report

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_lahi#12]
Make a new table from pmu_monthly_report table which has student info? 
    a. ongoing internship 11th and 12th - ongoing_11 and ongoing_12, boys and girls, 
    b. completed internship 11th and 12th -  boys and girls,
    c. exit survey 11 th and 1th, boys and girls
    d. guest lectures - for 9th to 12th 
    
    
<img width="1154" alt="Screenshot 2023-09-15 at 6 54 19 PM" src="https://github.com/DalgoT4D/dbt_lahi/assets/9019958/9fcba88b-cde9-4258-bc4d-5f64470b9093">

**Comment by Abhishek-N** [comment]
From the calculations we found `internships ongoing`, `exit survey`, `guest lectures`, `lab status`, `industrial visits` count looks good and is accurate

The count of `job mela`, `vt status`, `tot` we got different results than expected. 


Things to fix:

1. Job Mela: the count is given blank for boys and girls participants. what parameters should we use to calculate the total?

    have tried calculating with `job_mela_male_participated_10, job_mela_male_participated_12, 
    job_mela_female_participated_12, job_mela_female_participated_10, job_mela_male_offered_12, 
    job_mela_female_offered_10, job_mela_female_offered_12,  job_mela_male_offered_10
    `
    still the count looks very low

2. VT Status: the parameters given are not matching to those in the db. Also it is shown Internship ongoing class, should we find `vt approved` and `vt appointed` using the same? how?

3. TOT: the parameters shown and the ones is db is matched but the total count differs
