### ISSUE TITLE
Aggregation of data across all the states - LAHI (Catalyst Dashboard)

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_lahi#16]
![Image](https://github.com/DalgoT4D/dbt_lahi/assets/9019958/9de8a99f-895e-4d52-9158-0666d221b176)

- We need the following things for all the states 

1. Vocational education schools
2. Vocational Trainer Program (VTPs)
3. Vocation Trainer (VT)
4. Sectors 
5. Job roles (9th to 10th)
6. Job roles (11th to 12th)
7.  Total Boys
8. Total Girls
9. Grand Total (Boys + Girls)

**Comment by Abhishek-N** [comment]
1. Vocational education schools: looks good

2. VTP: `NA`, `No information available`, `Not available`

3. VT: `No information available', `NULL`, `NA`

4. Sectors: `NULL`

5. Job roles (9th to 10th): `No information available`, `NA`, `NULL`

6. Job roles (11th to 12th): `NULL`, `NA`

7. Total Boys: `NULL`

8. Total Girls: `NULL`

9. Grand Total (Boys + Girls): `NULL`

**Comment by siddhant3030** [comment]
Something like this will help you get rows with only valid values


SELECT * FROM union_state
WHERE 
column1 NOT IN ('NA', 'No information available', 'Not available')
AND 
column2 NOT IN ('NA', 'No information available', 'Null')
AND
column3 NOT IN ('NA', 'No information available', 'NA');

**Comment by Abhishek-N** [comment]
1. VE schools - 5937
2. VTPs - 68
3. VT - 3487
4. Sectors - 35
5. Job roles (9th to 10th) - 86
6. Job roles (11th to 12th) - 49
7. Total boys - 258
8. Total girls - 279
9. Grand total - 333

**Comment by siddhant3030** [comment]
So we need a grand total of each state. basically sum the rows to get this

**Comment by Abhishek-N** [comment]
Grand total:
Andhra Pradesh - 57127
Assam - 74831
Chhattisgarh - 116225
Delhi - 125118
Gujarat - 42903
Himachal Pradesh - 77932
Karnataka - 22092
Maharashtra - 68229
Uttarakhand - 37052


Total boys:
Andhra Pradesh - 23727
Assam - 36092
Chhattisgarh - 50334
Delhi - 52230
Gujarat - 19423
Himachal Pradesh - 0
Karnataka - 10986
Maharashtra - 31286
Uttarakhand - 17356


Total Girls:
Andhra Pradesh - 33400
Assam - 38739
Chhattisgarh - 65891
Delhi - 72888
Gujarat - 23541
Himachal Pradesh - 0
Karnataka - 11106
Maharashtra - 36943
Uttarakhand - 19696

**Comment by siddhant3030** [comment]
@Abhishek-N can you also add 
1. job_roles calculation for both 9th-10th and 11th-12th
2. school name calculation 

We will try to compare it and fix it if something is wrong

**Comment by Abhishek-N** [comment]
1. job_roles calculation for both 9th-10th and 11th-12th = 86 + 61 = 147
2. school name calculation = 5937

**Comment by siddhant3030** [comment]
@Abhishek-N hey. We need to mention job roles separately for each one basically for 9th and 10th then 11th and 12th

**Comment by Abhishek-N** [comment]
yes 86 and 61 for 9th to 10th and 11th to 12th resp.
